### ISSUE TITLE
networking/ntp fails

### ISSUE THREAD

**Issue by antlassagne** [canonical/checkbox#1963]
### Bug Description

When running the test networking/ntp from snap-installed checkbox, it fails.

### Cert-blocker Test Case

- [x] cert-blocker

### To Reproduce

Launcher file to reproduce:
```
        #!/usr/bin/env checkbox-cli
        [launcher]
        launcher_version = 1
        stock_reports = submission_json
        [test plan]
        forced = yes
        unit = com.canonical.certification::networking-cert-automated
        [test selection]
        forced = yes
        match=com.canonical.certification::networking/ntp
```

### Expected Result

Running instead
```
checkbox.shell
sudo python3 /snap/checkbox24/815/providers/checkbox-provider-base/bin/network_ntp_test.py
```
works fine, as well as just
```
sudo python3 /snap/checkbox24/815/providers/checkbox-provider-base/bin/network_ntp_test.py
```

A good output is something like 
```
2025-06-17 13:17:58 INFO     Pre-sync time is: Tue Jun 17 13:17:58 2025
2025-06-17 13:17:59 INFO     Successful NTP update from ntp.ubuntu.com
2025-06-17 13:17:59 INFO     Current system time is: Tue Jun 17 13:17:59 2025
```

### Actual Result

```
2025-06-17 16:38:27 INFO     Pre-sync time is: Tue Jun 17 16:38:27 2025
2025-06-17 16:38:27 ERROR    Failed to sync with ntp.ubuntu.com
2025-06-17 16:38:27 ERROR    ntpdig: can't find Python NTP library -- check PYTHONPATH.
No module named 'ntp'
2025-06-17 16:38:27 INFO     Current system time is: Tue Jun 17 16:38:27 2025
```

### Environment

Noble and checkbox snap (beta)

### Relevant log output

```shell

```

**Comment by Hook25** [comment]
Feel free to reopen this if it is still current, it should be fixed now

**Comment by pietro028** [comment]
I am still seeing the error.

OS: Ubuntu 26.04 LTS
Checkbox Version: 7.5.0-dev34
